//LISTA DE ACCIONES QUE HAREMOS PARA MANIPULA NUESTRO ESTADO GLOBAL

export const
    // SOLICITUDES    
    GET_ALL_POKEMONS = "GET_ALL_POKEMONS",
    GET_POKEMON_TYPES = "GET_POKEMON_TYPES",

    // FILTROS
    FILTER_POKEMONS = "FILTER_POKEMONS",
    RESET_FILTER = "RESET_FILTER",

    //EVENTOS
    NOT_SUCCESFUL_RESPONSE = "NOT_SUCCESFUL_RESPONSE"


