//LISTA DE ACCIONES QUE HAREMOS PARA MANIPULA NUESTRO ESTADO GLOBAL

export const
    // SOLICITUDES
    GET_ALL_POKEMONS = "GET_ALL_POKEMONS",
    GET_POKEMON_BY_ID = "GET_POKEMON_BY_ID",
    GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME",
    GET_POKEMON_TYPES = "GET_POKEMON_TYPES",

    // FILTROS
    FILTER_POKEMON_BY_TYPE = "FILTER_POKEMON_BY_TYPE",

    //ORDENADOS
    SORT_POKEMON_BY_NAME_ASC = "SORT_POKEMON_BY_NAME_ASC",
    SORT_POKEMON_BY_NAME_DES = "SORT_POKEMON_BY_NAME_DES",
    SORT_POKEMON_BY_STRENGTH_ASC = "SORT_POKEMON_BY_STRENGTH_ASC",
    SORT_POKEMON_BY_STRENGTH_DES = "SORT_POKEMON_BY_STRENGTH_DES"

